// -------------------------------------------------------------
// 
// File Name: C:\Users\user\Documents\MATLAB\Test\lab2\lab2_fixp\comp_fixpoint.v
// Created: 2022-11-30 08:03:48
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// O_valid                       ce_out        1
// O_magnitude                   ce_out        1
// O_phase                       ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: comp_fixpoint
// Source Path: lab2_fixp/comp_fixpoint
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module comp_fixpoint
          (clk,
           reset,
           clk_enable,
           I_valid,
           I_complex_value_re,
           I_complex_value_im,
           ce_out,
           O_valid,
           O_magnitude,
           O_phase);


  input   clk;
  input   reset;
  input   clk_enable;
  input   I_valid;
  input   [31:0] I_complex_value_re;  // ufix32_En22
  input   [31:0] I_complex_value_im;  // ufix32_En22
  output  ce_out;
  output  O_valid;
  output  [32:0] O_magnitude;  // ufix33_En21
  output  [15:0] O_phase;  // ufix16_En13


  wire enb;
  reg  [0:32] delayMatch_reg;  // ufix1 [33]
  wire [0:32] delayMatch_reg_next;  // ufix1 [33]
  wire I_valid_1;
  wire [63:0] Product_out1;  // ufix64_En44
  wire [63:0] Product1_out1;  // ufix64_En44
  wire [63:0] Add_out1;  // ufix64_En44
  wire [32:0] Sqrt_out1;  // ufix33_En21
  wire signed [32:0] Data_Type_Conversion1_out1;  // sfix33_En22
  wire signed [32:0] Data_Type_Conversion2_out1;  // sfix33_En22
  wire signed [32:0] Atan2_out1;  // sfix33_En30
  wire [15:0] Data_Type_Conversion_out1;  // ufix16_En13
  reg [15:0] delayMatch1_reg [0:9];  // ufix16 [10]
  wire [15:0] delayMatch1_reg_next [0:9];  // ufix16_En13 [10]
  wire [15:0] Data_Type_Conversion_out1_1;  // ufix16_En13


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 1'b0;
        delayMatch_reg[1] <= 1'b0;
        delayMatch_reg[2] <= 1'b0;
        delayMatch_reg[3] <= 1'b0;
        delayMatch_reg[4] <= 1'b0;
        delayMatch_reg[5] <= 1'b0;
        delayMatch_reg[6] <= 1'b0;
        delayMatch_reg[7] <= 1'b0;
        delayMatch_reg[8] <= 1'b0;
        delayMatch_reg[9] <= 1'b0;
        delayMatch_reg[10] <= 1'b0;
        delayMatch_reg[11] <= 1'b0;
        delayMatch_reg[12] <= 1'b0;
        delayMatch_reg[13] <= 1'b0;
        delayMatch_reg[14] <= 1'b0;
        delayMatch_reg[15] <= 1'b0;
        delayMatch_reg[16] <= 1'b0;
        delayMatch_reg[17] <= 1'b0;
        delayMatch_reg[18] <= 1'b0;
        delayMatch_reg[19] <= 1'b0;
        delayMatch_reg[20] <= 1'b0;
        delayMatch_reg[21] <= 1'b0;
        delayMatch_reg[22] <= 1'b0;
        delayMatch_reg[23] <= 1'b0;
        delayMatch_reg[24] <= 1'b0;
        delayMatch_reg[25] <= 1'b0;
        delayMatch_reg[26] <= 1'b0;
        delayMatch_reg[27] <= 1'b0;
        delayMatch_reg[28] <= 1'b0;
        delayMatch_reg[29] <= 1'b0;
        delayMatch_reg[30] <= 1'b0;
        delayMatch_reg[31] <= 1'b0;
        delayMatch_reg[32] <= 1'b0;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
          delayMatch_reg[2] <= delayMatch_reg_next[2];
          delayMatch_reg[3] <= delayMatch_reg_next[3];
          delayMatch_reg[4] <= delayMatch_reg_next[4];
          delayMatch_reg[5] <= delayMatch_reg_next[5];
          delayMatch_reg[6] <= delayMatch_reg_next[6];
          delayMatch_reg[7] <= delayMatch_reg_next[7];
          delayMatch_reg[8] <= delayMatch_reg_next[8];
          delayMatch_reg[9] <= delayMatch_reg_next[9];
          delayMatch_reg[10] <= delayMatch_reg_next[10];
          delayMatch_reg[11] <= delayMatch_reg_next[11];
          delayMatch_reg[12] <= delayMatch_reg_next[12];
          delayMatch_reg[13] <= delayMatch_reg_next[13];
          delayMatch_reg[14] <= delayMatch_reg_next[14];
          delayMatch_reg[15] <= delayMatch_reg_next[15];
          delayMatch_reg[16] <= delayMatch_reg_next[16];
          delayMatch_reg[17] <= delayMatch_reg_next[17];
          delayMatch_reg[18] <= delayMatch_reg_next[18];
          delayMatch_reg[19] <= delayMatch_reg_next[19];
          delayMatch_reg[20] <= delayMatch_reg_next[20];
          delayMatch_reg[21] <= delayMatch_reg_next[21];
          delayMatch_reg[22] <= delayMatch_reg_next[22];
          delayMatch_reg[23] <= delayMatch_reg_next[23];
          delayMatch_reg[24] <= delayMatch_reg_next[24];
          delayMatch_reg[25] <= delayMatch_reg_next[25];
          delayMatch_reg[26] <= delayMatch_reg_next[26];
          delayMatch_reg[27] <= delayMatch_reg_next[27];
          delayMatch_reg[28] <= delayMatch_reg_next[28];
          delayMatch_reg[29] <= delayMatch_reg_next[29];
          delayMatch_reg[30] <= delayMatch_reg_next[30];
          delayMatch_reg[31] <= delayMatch_reg_next[31];
          delayMatch_reg[32] <= delayMatch_reg_next[32];
        end
      end
    end

  assign I_valid_1 = delayMatch_reg[32];
  assign delayMatch_reg_next[0] = I_valid;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];
  assign delayMatch_reg_next[2] = delayMatch_reg[1];
  assign delayMatch_reg_next[3] = delayMatch_reg[2];
  assign delayMatch_reg_next[4] = delayMatch_reg[3];
  assign delayMatch_reg_next[5] = delayMatch_reg[4];
  assign delayMatch_reg_next[6] = delayMatch_reg[5];
  assign delayMatch_reg_next[7] = delayMatch_reg[6];
  assign delayMatch_reg_next[8] = delayMatch_reg[7];
  assign delayMatch_reg_next[9] = delayMatch_reg[8];
  assign delayMatch_reg_next[10] = delayMatch_reg[9];
  assign delayMatch_reg_next[11] = delayMatch_reg[10];
  assign delayMatch_reg_next[12] = delayMatch_reg[11];
  assign delayMatch_reg_next[13] = delayMatch_reg[12];
  assign delayMatch_reg_next[14] = delayMatch_reg[13];
  assign delayMatch_reg_next[15] = delayMatch_reg[14];
  assign delayMatch_reg_next[16] = delayMatch_reg[15];
  assign delayMatch_reg_next[17] = delayMatch_reg[16];
  assign delayMatch_reg_next[18] = delayMatch_reg[17];
  assign delayMatch_reg_next[19] = delayMatch_reg[18];
  assign delayMatch_reg_next[20] = delayMatch_reg[19];
  assign delayMatch_reg_next[21] = delayMatch_reg[20];
  assign delayMatch_reg_next[22] = delayMatch_reg[21];
  assign delayMatch_reg_next[23] = delayMatch_reg[22];
  assign delayMatch_reg_next[24] = delayMatch_reg[23];
  assign delayMatch_reg_next[25] = delayMatch_reg[24];
  assign delayMatch_reg_next[26] = delayMatch_reg[25];
  assign delayMatch_reg_next[27] = delayMatch_reg[26];
  assign delayMatch_reg_next[28] = delayMatch_reg[27];
  assign delayMatch_reg_next[29] = delayMatch_reg[28];
  assign delayMatch_reg_next[30] = delayMatch_reg[29];
  assign delayMatch_reg_next[31] = delayMatch_reg[30];
  assign delayMatch_reg_next[32] = delayMatch_reg[31];



  assign O_valid = I_valid_1;

  assign Product_out1 = I_complex_value_re * I_complex_value_re;



  assign Product1_out1 = I_complex_value_im * I_complex_value_im;



  assign Add_out1 = Product_out1 + Product1_out1;



  Sqrt u_Sqrt (.clk(clk),
               .reset(reset),
               .enb(clk_enable),
               .din(Add_out1),  // ufix64_En44
               .dout(Sqrt_out1)  // ufix33_En21
               );

  assign O_magnitude = Sqrt_out1;

  assign Data_Type_Conversion1_out1 = {1'b0, I_complex_value_im};



  assign Data_Type_Conversion2_out1 = {1'b0, I_complex_value_re};



  atan2_cordic_nw u_Atan2_inst (.clk(clk),
                                .reset(reset),
                                .enb(clk_enable),
                                .y_in(Data_Type_Conversion1_out1),  // sfix33_En22
                                .x_in(Data_Type_Conversion2_out1),  // sfix33_En22
                                .angle(Atan2_out1)  // sfix33_En30
                                );

  assign Data_Type_Conversion_out1 = Atan2_out1[32:17] + (Atan2_out1[16] & (( ~ Atan2_out1[32]) | (|Atan2_out1[15:0])));



  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg[0] <= 16'b0000000000000000;
        delayMatch1_reg[1] <= 16'b0000000000000000;
        delayMatch1_reg[2] <= 16'b0000000000000000;
        delayMatch1_reg[3] <= 16'b0000000000000000;
        delayMatch1_reg[4] <= 16'b0000000000000000;
        delayMatch1_reg[5] <= 16'b0000000000000000;
        delayMatch1_reg[6] <= 16'b0000000000000000;
        delayMatch1_reg[7] <= 16'b0000000000000000;
        delayMatch1_reg[8] <= 16'b0000000000000000;
        delayMatch1_reg[9] <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= delayMatch1_reg_next[0];
          delayMatch1_reg[1] <= delayMatch1_reg_next[1];
          delayMatch1_reg[2] <= delayMatch1_reg_next[2];
          delayMatch1_reg[3] <= delayMatch1_reg_next[3];
          delayMatch1_reg[4] <= delayMatch1_reg_next[4];
          delayMatch1_reg[5] <= delayMatch1_reg_next[5];
          delayMatch1_reg[6] <= delayMatch1_reg_next[6];
          delayMatch1_reg[7] <= delayMatch1_reg_next[7];
          delayMatch1_reg[8] <= delayMatch1_reg_next[8];
          delayMatch1_reg[9] <= delayMatch1_reg_next[9];
        end
      end
    end

  assign Data_Type_Conversion_out1_1 = delayMatch1_reg[9];
  assign delayMatch1_reg_next[0] = Data_Type_Conversion_out1;
  assign delayMatch1_reg_next[1] = delayMatch1_reg[0];
  assign delayMatch1_reg_next[2] = delayMatch1_reg[1];
  assign delayMatch1_reg_next[3] = delayMatch1_reg[2];
  assign delayMatch1_reg_next[4] = delayMatch1_reg[3];
  assign delayMatch1_reg_next[5] = delayMatch1_reg[4];
  assign delayMatch1_reg_next[6] = delayMatch1_reg[5];
  assign delayMatch1_reg_next[7] = delayMatch1_reg[6];
  assign delayMatch1_reg_next[8] = delayMatch1_reg[7];
  assign delayMatch1_reg_next[9] = delayMatch1_reg[8];



  assign O_phase = Data_Type_Conversion_out1_1;

  assign ce_out = clk_enable;

endmodule  // comp_fixpoint

